Add support for Permanent Delegate extension
wen-community/wen-new-standard pull request #28
Opened 2024-02-28 01:03 UTC by Aiyualive

Changes
- Add additional_extensions to CreateMintArgs
- Add optional permanent_delegate account
- Add initialization for permanent_delegate extension. If no perm delegate was provided return an error

Assumptions:
- `update_account_lamports_to_minimum_balance` will add extra sizing for added extensions

Blockers:
- Anchor cannot serialize CreateMintArgs with `additional_extensions: ExtensionsVec`, since `ExtensionType` is not supported by Anchor

2024-03-01 14:44 UTC, Bhargavamacha commented
Hey @Aiyualive thanks for the PR! Could you checkout [this](https://github.com/bridgesplit/anchor/blob/master/tests/spl/token-extensions/programs/token-extensions/src/instructions.rs) reference implementation and try to initialize permanent delegate instead of executing a separation instruction. Let me know if you have any issues.

2024-03-02 13:19 UTC, Aiyualive commented
Gm @Bhargavamacha! Thank you for swiftly looking into this!

I just looked into your reference and have the following questions:
- All mints are forced to have those specified MINT_EXTENSIONS, which is not that flexible. Wouldn't it be better to allow for some more flexibility in which extensions you would want?

- Since permanent delegate can never be changed, I think it would be nice to have this account be passed in as an optional account. What do you think?

- If the permanent_delegate is optional, how would you pass that into the macro:
 extensions::permanent_delegate::delegate = permanent_delegate.key()?

2024-03-04 13:39 UTC, luke-truitt commented
Bridgesplit is going to update the Anchor fork to support optional extension initialization in the macro, once this is live it should resolve this issue. Will tag here once that's complete

2024-03-11 23:31 UTC, Aiyualive commented
- I wanted to assign `Pubkey::default()` as the default permanent delegate in case no argument was passed in, although this led to an invalid program argument. We experienced similar issues previously when trying ti simply assign the default pubkey as the transfer hook program. So I think there are some limitations with the use thereof.

- I also added accommodated some tests for the manager account for local testing.

2024-03-12 20:20 UTC, Bhargavamacha requested changes

2024-03-12 20:20 UTC, Bhargavamacha commented on programs/wen_new_standard/src/instructions/mint/create.rs
> +        extensions::permanent_delegate::delegate = args.permanent_delegate.unwrap_or_else(|| manager.key()),
I dont think we should leave permanent delegate as manager if user chose not to use it, can you add an update permanent delegate below to remove it if the argument passed is None

2024-03-12 20:20 UTC, Bhargavamacha commented on clients/wns-sdk/tests/e2e.test.ts
> +			instructions: [createGroupIx, addDistributionIx],
please run lint

2024-03-12 21:18 UTC, luke-truitt approved these changes

2024-03-13 00:09 UTC, balmy-gazebo approved these changes

2024-03-13 13:02 UTC, merged