Bob/modify burn
wen-community/wen-new-standard pull request #46
Opened 2024-03-17 17:54 UTC by Aiyualive

The burn ix has too much responsibility. So I removed the functionality of `close_token_account`. The user can close this account on his/her own accord.

2024-03-17 18:53 UTC, kespinola requested changes
Is the CU for the instruction high? The UX of having the TA closed along with the other accounts is natural and reduces the burden on the caller.

2024-03-17 19:31 UTC, Aiyualive commented
I suppose the CUs should be reduced now since we are removing an instruction.

Fundamentally I think the instruction should be as light-weight as possible and only contain the required logic for its purpose

By including the close_token_account instruction it also limits composability from other programs, which is essentially why I am suggesting this change.

2024-03-17 20:46 UTC, Aiyualive commented
Another noteworthy change is changing anchor constraints from this
```
        associated_token::token_program = token_program,
        associated_token::mint = mint,
        associated_token::authority = user,
```
to this 
```
        token::mint = mint.key(),
        token::token_program = token_program.key(),
```

This has negligible impact as the authority checks happen in the T22 burn ix. 
Also with this change, the permanent delegate can now burn the token as well.

2024-03-18 01:27 UTC, Aiyualive commented
> Is the CU for the instruction high? The UX of having the TA closed along with the other accounts is natural and reduces the burden on the caller.

On another note, the integrator could simply include the closing ix of the associated token oneself as a part of the tx

2024-03-18 09:15 UTC, kespinola commented
> I.e. you will not be able to burn the NFT with the permanent delegate - since the permanent delegate is not the authority of the token account.

Good point on this though I'm not sure giving delegates burn rights is good call. What are some operations where a delegate would want to a burn? Giving delegate rights to burn seems over permissive at first thought.

2024-03-18 09:44 UTC, Aiyualive commented
I added the PR of having optional Permanent Delegate Extension: [here](https://github.com/wen-community/wen-new-standard/pull/28), in order to allow for burning with the Permanent Delegate Extension.

I am building epplex, where the idea is to allow for permissionless burning of an NFT given certain open-sourced conditions. This use-case is what we are demonstrating with [Burger Game](https://twitter.com/blessed_burgers) and i think this would be a perfect fit as an example application for WNS.

Alternatively, if you are adamant on keeping the `close_token_account`, it would be even better for our use-case to include an ix that changes the `CloseMintAuthority` type, then we could simply burn through the Token2022 program directly.

2024-03-18 11:26 UTC, Aiyualive commented
Sounds good! 

Yes, so I have implemented the burn through WNS currently: simply CPI'ing into the WNS burn ix.

With that said, do you think we can merge the PR?

2024-03-18 11:41 UTC, kespinola commented
> With that said, do you think we can merge the PR?

I think the deletion of the ata should be handled by the burn but delegation rights should be adjusted. This needs more thought but based on my working with cNFTs the best DX is to have the entry point program maintain authority of all assets it interacts with like how bubblegum is the delegate on the merkle trees and access control managed through entry point program (eg bubblegum, wns).

Love to hear some other folks thoughts.

2024-03-18 13:36 UTC, balmy-gazebo commented
One other thing to think about is that you could accomplish this functionality by transferring token to the account you have write privileges for using permanent delegate and then calling burn on it. Might be more natural.

2024-03-19 13:11 UTC, balmy-gazebo commented
@Aiyualive can we close this?

2024-04-16 16:13 UTC, balmy-gazebo commented
No movement here so closing for now. Can re-open if it becomes relevant.

2024-04-16 16:13 UTC, closed without merging